### ISSUE TITLE
NLog FileTarget KeepFileOpen = false by default

### ISSUE THREAD

**Issue by snakefoot** [wddpct/LoggingPerformance#1]
Please update the non-optimal NLog config:

https://github.com/wddpct/LoggingPerformance/blob/0df48dd36e04bf6b9631332e421d4400dd84d1a9/LoggingPerformance.NLog/Program.cs#L25-L29

So it matches Serilog configuration values (Tells NLog NOT to open/close file for each logevent, and only flush every second):

```c#
 var fileTarget = new FileTarget 
 { 
     Name = "FileTarget", 
     FileName = "Log.txt",
     KeepFileOpen = true,
     ConcurrentWrites = false,
     AutoFlush = false,
     OpenFileFlushTimeout = 1,
}; 
```

Also remove the usage of `BufferingTargetWrapper`  as it is used for throttle (Ex limiting the number of http-requests or emails), and not for performance:

https://github.com/wddpct/LoggingPerformance/blob/0df48dd36e04bf6b9631332e421d4400dd84d1a9/LoggingPerformance.NLog/Program.cs#L30-L35

**Comment by snakefoot** [comment]
@wddpct See also my comments here: https://www.darylcumbo.net/serilog-vs-nlog-benchmarks/

**Comment by snakefoot** [comment]
NLog 4.5.7 + LibLog 5.0.2 + Serilog 2.7.1

| 1 Thread - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- | ------------- |
| Serilog | 207781 msgs/sec | 4,782mcs | 7.553 MBytes | 23,1 sec |
| NLog  | 273648 msgs/sec | 3,621mcs | 4.502 MBytes | 18,3 sec |
| NLog Async  | 407117 msgs/sec | 2,399mcs  | 4.532 MBytes | 18,4 sec |

| 2 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog  | 276712 msgs/sec | 7,162mcs | 7.597 MBytes | 33,5 sec |
| NLog  | 323692 msgs/sec | 6,092mcs | 4.525 MBytes | 30,3 sec |
| NLog Async | 384942 msgs/sec | 4,734mcs | 4.555 MBytes | 18,3 sec |

| 4 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog  | 272994 msgs/sec | 14,502mcs | 7.618 MBytes | 65,6 sec |
| NLog  | 322585 msgs/sec | 12,116mcs | 4.539 MBytes | 59,0 sec |
| NLog Async | 348736 msgs/sec | 10,291mcs | 4.571 MBytes | 22,7 sec |

| 8 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog  | 270654 msgs/sec | 29,141mcs | 7.656 MBytes | 68,7 sec |
| NLog  | 320143 msgs/sec | 24,618mcs | 4.561 MBytes | 61,5 sec |
| NLog Async | 284317 msgs/sec | 26,216mcs | 4.596 MBytes | 34,8 sec |

**NLog Async** = `AsyncTargetWrapper { TimeToSleepBetweenBatches = 0, OverflowAction = Block, BatchSize = 500 }`

P.S. Update the performance tests with release of NLog 4.6: https://github.com/wddpct/LoggingPerformance/issues/1#issuecomment-476013097

**Comment by 304NotModified** [comment]
bump @wddpct

**Comment by 304NotModified** [comment]
@snakefoot maybe we could make a PR for this?

**Comment by 304NotModified** [comment]
I will create a PR

**Comment by panchengtao** [comment]
@snakefoot thanks for your advise and sorry for my  negligence. I'll check it soon later.

**Comment by snakefoot** [comment]
@wddpct Should keep this issue open until the **Readme.md** shows the updated numbers.

**Comment by 304NotModified** [comment]
Another issue to update the readme is also an option

**Comment by snakefoot** [comment]
Created  #3

**Comment by snakefoot** [comment]
NLog 4.6 + LibLog 5.0.4 + Serilog 2.8.0

`<ServerGarbageCollection>true</ServerGarbageCollection>`

| 1 Thread - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- | ------------- |
| Serilog NetCore21 | 191754 msgs/sec | 5,180mcs | 5.683 MBytes | 25,3 sec |
| Serilog Async NetCore21 | 323920 msgs/sec | 3,059mcs | 5.683 MBytes | 26,4 sec |
| NLog NetCore21  | 324633 msgs/sec | 3,051mcs | 3.776 MBytes | 15,4 sec |
| NLog Async NetCore21 | 697145 msgs/sec | 1,408mcs  | 3.777 MBytes | 13,8 sec |

| 2 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog NetCore21  | 293760 msgs/sec | 6,767mcs | 5.683 MBytes | 28,9 sec |
| Serilog Async NetCore21 | 285316 msgs/sec | 6,919mcs | 5.683 MBytes | 41,8 sec |
| NLog NetCore21  | 481635 msgs/sec | 4,116mcs | 3.776 MBytes | 19,6 sec |
| NLog Async NetCore21 | 680265 msgs/sec | 2,906mcs | 3.777 MBytes | 13,3 sec |

| 4 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog NetCore21 | 240422 msgs/sec | 16,533mcs | 5.683 MBytes | 53,6 sec |
| Serilog Async NetCore21 | 235433 msgs/sec | 16,864mcs | 5.683 MBytes | 61,0 sec |
| NLog NetCore21  | 406490 msgs/sec | 9,710mcs | 3.776 MBytes | 34,7 sec |
| NLog Async NetCore21 | 663800 msgs/sec | 5,957mcs | 3.777 MBytes | 12,6 sec |

| 8 Threads - 5.000.000 msgs | Throughput | Mean Latency | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | -------------- | ------------- |
| Serilog NetCore21  | 219048 msgs/sec | 36,382mcs | 5.683 MBytes | 58,7 sec |
| Serilog Async NetCore21 | 222894 msgs/sec | 35,563mcs | 5.683 MBytes | 67,1 sec |
| NLog NetCore21  | 404564 msgs/sec | 19,581mcs | 3.776 MBytes | 34,3 sec |
| NLog Async NetCore21 | 638214 msgs/sec | 12,425mcs | 3.777 MBytes | 13,0 sec |

**NLog Async** = `AsyncTargetWrapper { TimeToSleepBetweenBatches = 0, OverflowAction = Block, BatchSize = 500 }`

**Serilog Async** = `WriteTo.Async(a => a.File("Log.txt", buffered: true, flushToDiskInterval: TimeSpan.FromMilliseconds(1000)), blockWhenFull: true);`

P.S. LibLog ver. 5.0.5 has bug that causes extra overhead for the NLog-provider. See also https://github.com/damianh/LibLog/pull/233 (This has been fixed with LibLog ver. 5.0.8)

**Comment by snakefoot** [comment]
NLog 4.6.8 + LibLog 5.0.8 + Serilog 2.9.0

`<ServerGarbageCollection>true</ServerGarbageCollection>`

| 1 Thread - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog NetCore3 | 169.929 msgs/sec | 6.027 MBytes | 28.7 sec |
| Serilog Async NetCore3 | 320.433 msgs/sec | 4.921 MBytes | 29.9 sec |
| NLog NetCore3 | 269.128 msgs/sec | 5.188 MBytes | 18.8 sec |
| NLog Async NetCore3 | 516.632 msgs/sec | 5.188 MBytes | 14.6 sec |

| 2 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog NetCore3 | 285.567 msgs/sec |  6.014 MBytes | 32.5 sec |
| Serilog Async NetCore3 | 388.871 msgs/sec | 5.878 MBytes | 34.8 sec |
| NLog NetCore3 | 435.336 msgs/sec | 5.169 MBytes | 22.4 sec |
| NLog Async NetCore3 | 682.530 msgs/sec | 5.185 MBytes | 17.5 sec |

| 4 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog NetCore3 | 298.070 msgs/sec | 6.017 MBytes | 51.6 sec |
| Serilog Async NetCore3 | 278.130 msgs/sec | 5.882 MBytes | 60.6 sec |
| NLog NetCore3 | 432.278 msgs/sec | 5.172 MBytes | 36.5 sec |
| NLog Async NetCore3 | 680.986 msgs/sec | 5.186 MBytes | 16.0 sec |

| 8 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog NetCore3 | 287.186 msgs/sec | 6.016 MBytes | 55.8 sec |
| Serilog Async NetCore3 | 256.226 msgs/sec | 5.935 MBytes | 65.2 sec |
| NLog NetCore3 | 392.772 msgs/sec | 5.175 MBytes | 40.4 sec |
| NLog Async NetCore3 | 676.667 msgs/sec | 5.186 MBytes | 14.9 sec |

**NLog Async** = `AsyncTargetWrapper { TimeToSleepBetweenBatches = 0, OverflowAction = Block, BatchSize = 500 }`

**Serilog Async** = `WriteTo.Async(a => a.File("Log.txt", buffered: true, flushToDiskInterval: TimeSpan.FromMilliseconds(1000)), blockWhenFull: true);`

**Comment by PureKrome** [comment]
@snakefoot nice work! ~out of interest, is the test code available so we can run this ourselves, etc?~

EDIT: soz, i thought this issue was in the main nlog repo. code is all in _this_ repo. 😊

**Comment by snakefoot** [comment]
@PureKrome  Actually I cheated a little, and used the LibLogPerformance-test here (Had to upgrade dependencies and change TargetFramework to netcoreapp3):

https://github.com/NLog/NLog-Performance-tests

I find that the test-code in pcTOR's repo spent most time on individual logevent-timings, instead of throughput (Not worried about performance of a single log-event). Also I like to capture cpu-usage and memory-allocation (not very easy when multithreaded-testing on NetCore).

**Comment by jdeehrnth** [comment]
@snakefoot   The throughput numbers on Dec 4 now have a decimal point in them (1/1000 of previous throughput numbers).  Is this a typo?

**Comment by 304NotModified** [comment]
I guess a cultural/regional issue. Europe uses a dot as thousand separator and US uses a comma ;)

**Comment by jdeehrnth** [comment]
@304NotModified   Ah, I didn't think of that.  Thanks.  The previous tests results had no separator, so no confusion.  :-)

**Comment by snakefoot** [comment]
NET6.0.300 + NLog 5.0.0 + LibLog 5.0.8 + Serilog 2.10.0

`<ServerGarbageCollection>true</ServerGarbageCollection>`

| 1 Thread - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog Net6 | 273.674 msgs/sec | 5.837 MBytes | 17.8 sec |
| Serilog Async Net6 | 433.617 msgs/sec | 5.837 MBytes | 21.6 sec |
| NLog Net6 | 421.958 msgs/sec | 4.119 MBytes | 11.9 sec |
| NLog Async Net6 | 555.391 msgs/sec | 4.121 MBytes | 9.5 sec |

| 2 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog Net6 | 399.763 msgs/sec |  5.825 MBytes | 22.7 sec |
| Serilog Async Net6 | 485.721 msgs/sec | 6.465 MBytes | 25.8 sec |
| NLog Net6 | 607.675 msgs/sec | 4.108 MBytes | 15.6 sec |
| NLog Async Net6 | 767.364 msgs/sec | 4.120 MBytes | 14.5 sec |

| 4 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog Net6 | 358.928 msgs/sec | 5.825 MBytes | 42.9 sec |
| Serilog Async Net6 | 337.501 msgs/sec | 6.571 MBytes | 49.6 sec |
| NLog Net6 | 604.161 msgs/sec | 4.108 MBytes | 27.1 sec |
| NLog Async Net6 | 524.178 msgs/sec | 4.118 MBytes | 6.6 sec |

| 8 Threads - 5.000.000 msgs | Throughput | Mem Allocated | Cpu Time |
| ---- | ----------------------- | -------------- | ------------- |
| Serilog Net6 | 388.662 msgs/sec | 5.824 MBytes | 43.0 sec |
| Serilog Async Net6 | 305.801 msgs/sec | 6.647 MBytes | 57.4 sec |
| NLog Net6 | 510.511 msgs/sec | 4.109 MBytes | 29.5 sec |
| NLog Async Net6 | 543.943 msgs/sec | 4.119 MBytes | 8.1 sec |

**NLog Async** = `AsyncTargetWrapper { TimeToSleepBetweenBatches = 0, OverflowAction = Block, BatchSize = 500 }`

**Serilog Async** = `WriteTo.Async(a => a.File("Log.txt", buffered: true, flushToDiskInterval: TimeSpan.FromMilliseconds(1000)), blockWhenFull: true);`

Notice I only have 4 CPU-cores, so when more than 4 threads, then lock-congestion issues is showing.

**Comment by PureKrome** [comment]
Wow - interesting results

**Comment by snakefoot** [comment]
Yes .NET6 (and also .NET5) gives much better performance without doing anything. The strange part was that .NET6 vanilla performed worse than .NET5, but now with NET6.0.300 then it is all good.

Should probably change to Microsoft LoggerFactory as abstraction in future benchmarks, since LibLog is now deprecated.

**Comment by snakefoot** [comment]
Changed from LibLog to Microsoft Extensions Logging and running with .NET v7.0.1

- NLog v5.1.1 + NLog.Extensions.Logging v5.2.1
- Serilog v2.1.2 + Serilog.Sinks.File v5 + Serilog.Sinks.Async v1.5 + Serilog.Extensions.Logging v3.1.0

| **1 Threads- 5.000.000 msgs** | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|--------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog            |    13.153 |   380.133 |   0 |   0 | 293 |   12.406 |    3.854,8 |
| Serilog Async    |     8.378 |   596.753 |   0 |  34 |  36 |   14.812 |    3.883,0 |
| Serilog Json Async |    16.435 |   304.215 |   2 |  56 | 319 |   26.375 |    8.721,4 |
| NLog             |     6.852 |   729.681 |   0 |   1 | 171 |    6.937 |    2.250,7 |
| NLog Async       |     5.250 |   952.333 |   1 |  30 |  42 |    7.171 |    2.251,4 |
| NLog Json Async    |    17.105 |   292.303 |   1 |  70 |  91 |   20.140 |    7.592,5 |

| **2 Threads - 5.000.000 msgs** | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|--------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog            |    10.583 |   504.066 |   0 |   0 | 288 |   17.375 |    3.855,6 |
| Serilog Async      |    10.028 |   498.581 |   0 |  39 |  40 |   26.312 |    4.473,6 |
| Serilog Json Async |    14.283 |   350.051 |   1 |  48 | 128 |   31.718 |    8.958,2 |
| NLog               |     6.531 |   831.742 |   0 |   1 | 167 |   11.515 |    2.250,7 |
| NLog Async         |    10.057 |   497.143 |   1 |  25 |  29 |    7.734  |    2.251,4 |
| NLog Json Async  |     9.785 |   510.985 |   1 |  56 |  65 |   22.609 |    7.592,0 |

| **4 Threads - 5.000.000 msgs** | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|--------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog          |    11.287 |   442.951 |   0 |   0 | 267 |   30.937 |    3.854,8 |
| Serilog Async    |    12.295 |   406.647 |   0 |  38 |  39 |   37.234 |    4.526,5 |
| Serilog Json Async |    13.938 |   358.730 |   0 |  51 |  60 |   34.203 |    9.064,2 |
| NLog             |     6.588 |   758.901 |   0 |   1 | 158 |   18.031 |    2.250,7 |
| NLog Async       |     7.139 |   700.280 |   1 |  28 |  31 |    7.640 |    2.251,4 |
| NLog Json Async | 6.640 | 752.899 | 1 | 38 | 41 | 23.265 | 7.593,5 |

**Comment by snakefoot** [comment]
Changed from LibLog to Microsoft Extensions Logging and running with .NET v8

- NLog v5.2.7 + NLog.Extensions.Logging v5.3.7
- Serilog v3.0.1  + Serilog.Sinks.File v5 + Serilog.Sinks.Async v1.5 + Serilog.Extensions.Logging v7 + Serilog.Formatting.Compact v1.1

| 1 Threads- 5.000.000 msgs         | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog          |    10.240 |   488.244 |   0 |   0 | 237 |    9.140 |    3.475,1 |
| Serilog Async    |     7.872 |   635.116 |   0 |  29 |  30 |   13.656 |    3.511,9 |
| Serilog Json Async |    13.106 |   381.498 |   1 |  34 | 419 |   21.156 |    8.598,5 |
| NLog             |     5.499 |   909.129 |   0 |   1 | 138 |    5.578 |    2.021,8 |
| NLog Async       |     3.974 | 1.257.881 |   0 |  25 |  39 |    6.296 |    2.022,5 |
| NLog Json Async  |    12.990 |   384.886 |   0 |  65 |  80 |   16.078 |    7.210,5 |

| 2 Threads- 5.000.000 msgs        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog          |     9.602 |   520.686 |   0 |   0 | 236 |   14.687 |    3.476,0 |
| Serilog Async    |     9.146 |   546.636 |   0 |  33 |  34 |   22.796 |    4.084,7 |
| Serilog Json Async |    12.535 |   398.875 |   0 |  43 | 128 |   29.062 |    9.007,0 |
| NLog             |     5.524 |   905.079 |   0 |   1 | 137 |   10.359 |    2.021,8 |
| NLog Async       |     3.139 | 1.592.367 |   0 |  17 |  18 |    7.640 |    2.022,7 |
| NLog Json Async  |     7.396 |   676.039 |   0 |  45 |  53 |   17.796 |    7.211,4 |

| 4 Threads- 5.000.000 msgs         | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog          |    11.519 |   434.045 |   0 |   0 | 237 |   29.125 |    3.474,2 |
| Serilog Async    |    14.854 |   336.602 |   0 |  34 |  35 |   46.515 |    4.155,6 |
| Serilog Json Async |    16.019 |   312.119 |   0 |  51 |  58 |   47.781 |    9.140,3 |
| NLog             |     6.054 |   825.856 |   0 |   0 | 138 |   17.234 |    2.021,8 |
| NLog Async       |     3.645 | 1.371.518 |   0 |  16 |  17 |    8.218 |    2.022,5 |
| NLog Json Async  |     7.424 |   673.486 |   0 |  24 |  25 |   21.093 |    7.210,6 |

Notice NLog Async performance numbers have improved a lot, by reducing the SpinLock-count when blocking on async-queue-full (Not caused by NET8 upgrade). Notice Serilog Async is probably slowed down by BlockingCollection (only handles one producer and one consumer), and will probably improve performance by changing to pipes/channels. Overall Serilog and NLog are performing very well, and if performance is super important then one should checkout ZLogger and ZeroLog (Or C++/Rust). See also: https://github.com/Cysharp/ZLogger/pull/127 (Though not as flexible as NLog/Serilog)

**Comment by shvez** [comment]
I've updated your perf test code to add log4net there and to use latest library versions for nlog and serilog. 

Versions:
NLog - 5.3.2
NLog.Extensions.Logging - 5.3.11

Serilog - 4.0.0
Serilog.Extensions.Logging - 8.0.0
Serilog.Formatting.Compact - 3.0.0
Serilog.Sinks.Async - 2.0.0
Serilog.Sinks.File - 6.0.0

log4net - 2.0.17
Microsoft.Extensions.Logging.Log4Net.AspNetCore - 8.0.0

Here are results:

```
Executing warmup run... (.NET=8.0.7+2aade6beb02ea367fd97c4070a4198802fe61c03, Platform=64bit)
Executing performance test...

| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| NLog             |  5 000 000 |   79 |    2 |       1 |


| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog             |     4 350 | 1 149 302 |   0 |   1 |  13 |    4 671 |    2 021,8 |
!!! Test completed too quickly, to give useful numbers !!!

Executing warmup run... (.NET=8.0.7+2aade6beb02ea367fd97c4070a4198802fe61c03, Platform=64bit)
Executing performance test...

| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| Serilog          |  5 000 000 |   79 |    2 |       1 |


| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| Serilog          |    20 062 |   249 222 |   0 |   0 |  23 |   19 796 |    3 550,4 |

Executing warmup run... (.NET=8.0.7+2aade6beb02ea367fd97c4070a4198802fe61c03, Platform=64bit)
Executing performance test...

| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| log4net          |  5 000 000 |   79 |    2 |       1 |


| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| log4net          |   434 866 |    11 497 |   0 |   0 |  33 |  431 921 |    5 267,3 |
```

the interesting thing is that it complains for NLog that it was too fast, although I see that file size is same as for others

UPD.: to run first test I ued `FileAppender` and it turned out to be very slow. Usage of RollingFileAppender gives us much better results for log4net:
```
| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| log4net          |    23 485 |   212 897 |   0 |   0 |  10 |   23 656 |    1 534,9 |
```

**Comment by snakefoot** [comment]
Microsoft Extensions Logging and running with .NET v10

- NLog v6.0.6 + NLog.Extensions.Logging v6.1.0
- Serilog v4.3.0  + Serilog.Sinks.File v7 + Serilog.Sinks.Async v2.1 + Serilog.Extensions.Logging v9.0.2 + Serilog.Formatting.Compact v3

| Simple 10.000.000 msgs         | Threads<br/>Logging| Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|--|-----------|-----------|-----|-----|-----|----------|------------|
| NLog | 1 |   4.251 | 2.352.123 |   0 |   0 |  24 |    4.265 |    3.192,5 |
| Serilog |  1 |   8.082 | 1.237.226 |   0 |   0 |  36 |    7.421 |    4.818,1 |
| NLog Async  | 1 |   3.382 | 2.956.704 |   1 |  13 |  26 |    5.359 |    3.277,5 |
| Serilog Async | 1 |  6.703 | 1.491.838 |   0 |  36 |  37 |   11.796 |    4.918,6 |
| NLog Async   | 2|    2.761 | 3.620.828 |   1 |  24 |  26 |    7.921 |    3.348,2 |
| Serilog Async | 2 |   8.081 | 1.237.446 |   0 |  44 |  45 |   21.390 |    5.993,6 |
| NLog Async  |  4 |     2.605 | 3.838.755 |   1 |  23 |  25 |    9.484 |    3.284,3 |
| Serilog Async | 4 |   10.845 |   922.077 |   0 |  44 |  45 |   30.468 |    6.011,4 |

| Json 5.000.000 msgs         | Threads<br/>Logging| Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|--|-----------|-----------|-----|-----|-----|----------|------------|
| NLog Json        | 1 |    5.548 |   901.205 |   0 |   0 |  17 |    5.593 |    2.225,9 |
| Serilog Json     |  1 |   7.140 |   700.217 |   0 |   0 |  47 |    6.500 |    6.146,3 |
| NLog Json Async  | 1 |    5.664 |   882.655 |   1 |  29 |  41 |    5.968 |    5.964,0 |
| Serilog Json Async | 1 |   6.719 |   744.150 |   0 |  46 |  47 |   10.890 |    6.227,1 |
| NLog Json Async   | 2|    3.979 | 1.256.335 |   1 |  29 |  36 |   10.718 |    5.996,6 |
| Serilog Json Async | 2 |    6.141 |   814.170 |   0 |  50 |  51 |   16.500 |    6.808,5 |
| NLog Json Async  |  4 |     2.798 | 1.786.491 |   1 |  17 |  19 |   12.687 |    6.025,3 |
| Serilog Json Async | 4 |    8.346 |   599.076 |   0 |  47 |  48 |   20.828 |    6.733,2 |

Have a new machine now, so hard to compare with previous keyfigures (exception the memory allocation). 

Had to increase to 10.000.000 Log-Messages when not formatting as Json, or else the tests would complete too quickly. But when comparing memory-allocation for Json-Formatting, then both NLog and Serilog have reduce their memory-allocations since last test. But also curious if NET10 is playing games, since the memory-allocation for NLog should remain the same for all Async-tests.

Like how NLog is able to scale as the number of logger-threads increases.

Guess I should consider to include ZLogger in this simple benchmark-suite.

**Comment by Mertsch** [comment]
> Guess I should consider to include ZLogger in this simple benchmark-suite.

Yes, please 🧡

**Comment by snakefoot** [comment]
Microsoft Extensions Logging and running with .NET v10

- NLog v6.1.0 + NLog.Extensions.Logging v6.1.1
- Serilog v4.3.1 + Serilog.Extensions.Logging v10 + Serilog.Sinks.File v7 + Serilog.Sinks.Async v2.1 + Serilog.Formatting.Compact v3
- ZLogger v2.5.10

Have adjusted the benchmark a little to introduce a throttle for the logger-threads, so not constantly testing the overflow-blocking-handling (since rare in normal applications), and trying to capture logging-overhead (context-capture / allocation / lock-congestion / etc.) when offloading to async background-writer-thread.

Have also added ZLogger to the benchmark, but it only supports Async-mode as background-writer-thread is always enabled.


| Simple 5.000.000 msgs         | Threads<br/>Logging| Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Logging<br/>Overhead | Alloc (MB) |
|------------------|--|-----------|-----------|-----|-----|-----|----------|----------|------------|
| NLog             | 1 |     2.256 | 2.216.520 |   0 |   0 |  12 |    2.343 |    2.250 |    1.614,2 |
| Serilog          | 1 |   4.050 | 1.234.591 |   0 |   0 |  15 |    4.015 |    4.049 |    1.957,0 |
| ZLogger Async    | 1 |     2.441 | 2.048.157 |   0 |   1 |   5 |    5.546 |    2.437 |      667,0 |
| NLog Async       | 1 |    1.499 | 3.336.220 |   0 |   4 |  12 |    2.703 |    1.493 |    1.653,7 |
| Serilog Async    | 1 |    3.349 | 1.492.915 |   0 |  14 |  15 |    6.812 |    3.344 |    2.046,8 |
| ZLogger Async    | 2 |    3.289 | 1.520.231 |   0 |   1 |   6 |   17.156 |    6.568 |      861,3 |
| NLog Async       | 2 |    1.391 | 3.593.550 |   0 |   7 |  12 |    3.765 |    2.770 |    1.682,7 |
| Serilog Async    | 2 |    4.498 | 1.111.684 |   1 |  17 |  19 |   11.468 |    8.891 |    2.537,8 |
| ZLogger Async    | 4 |    4.434 | 1.127.610 |   0 |   1 |   9 |   37.390 |   17.718 |    1.312,2 |
| NLog Async       | 4 |    1.291 | 3.872.735 |   0 |   7 |  12 |    4.453 |    5.131 |    1.659,4 |
| Serilog Async    | 4 |    5.080 |   984.233 |   0 |  18 |  19 |   14.953 |   20.237 |    2.536,0 |

| Json 5.000.000 msgs         | Threads<br/>Logging| Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Logging<br/>Overhead | Alloc (MB) |
|------------------|--|-----------|-----------|-----|-----|-----|----------|----------|------------|
| NLog         | 1 |    4.901 | 1.020.292 |   0 |   0 |  17 |    5.046 |    4.882 |    2.227,3 |
| Serilog       | 1 |   7.322 |   682.857 |   0 |   0 |  43 |    6.390 |    7.321 |    5.688,5 |
| ZLogger Async | 1 |    4.177 | 1.197.010 |   0 |   1 |   9 |   11.296 |    4.171 |    1.250,5 |
| NLog Async  | 1 |     3.368 | 1.484.697 |   0 |  16 |  26 |    5.343 |    3.353 |    3.456,5 |
| Serilog Async | 1|     5.148 |   971.285 |   0 |  43 |  44 |   10.343 |    5.138 |    5.777,8 |
| ZLogger Async | 2 |    5.148 |   971.168 |   0 |   1 |  12 |   29.437 |   10.283 |    1.682,8 |
| NLog Async  | 2 |    2.644 | 1.890.935 |   0 |  23 |  26 |    7.406 |    5.266 |    3.458,7 |
| Serilog Async | 2 |     5.862 |   852.998 |   0 |  47 |  48 |   16.156 |   11.592 |    6.352,5 |
| ZLogger Async | 4 |    5.633 |   887.608 |   0 |   1 |  14 |   42.765 |   22.505 |    1.922,2 |
| NLog Async  | 4 |    2.681 | 1.865.282 |   0 |  24 |  26 |    8.328 |   10.635 |    3.455,6 |
| Serilog Async | 4 |    7.813 |   639.976 |   0 |  46 |  47 |   20.234 |   31.076 |    6.270,9 |

NLog v6.1 introduces optimization to its JsonLayout to reduce the overhead of Json-Encoding, and also reduces memory-allocations when doing context-capture for async background-writer-thread. Have also made a small modification to NLog JsonLayout configuration in the benchmark to optimize for async background-writer-thread.

Again all logging libraries are performing very well and will not be holding back the application,, since most are usually happy when able to get 50000 requests/sec from a single thread in a .NET application. If low memory-allocation is critical then ZLogger is looking good, but ZLogger is also "cheating" as it doesn't correctly handle parameters that mutates after the log-statement (Ex. disposed / returned-to-pool / etc.) but the async-writer requires parameters to be immutable (Ex. string  / int / double / structs / etc.)

Interesting that memory-allocation for ZLogger / Serilog increases with higher thread-count. Maybe some thread-static-allocation is introduced for the application-threads when logging?
